### ISSUE TITLE
Mock up and app function rough design

### ISSUE THREAD

**Issue by dbandrews** [UBC-MDS/happy-dash#1]
Draw the app and decide on app functions

**Comment by aidanmattrick** [comment]
Here are the diagrams we have thus far:

[IMG_7322.HEIC.pdf](https://github.com/UBC-MDS/happy-dash/files/5817634/IMG_7322.HEIC.pdf)

[IMG_7328.HEIC.pdf](https://github.com/UBC-MDS/happy-dash/files/5817635/IMG_7328.HEIC.pdf)

**Comment by aidanmattrick** [comment]
[Overview.pdf](https://github.com/UBC-MDS/happy-dash/files/5817648/Overview.pdf)
[Detailed View.pdf](https://github.com/UBC-MDS/happy-dash/files/5817649/Detailed.View.pdf)

Edits for Overall slide:
- Toggle for features in Overall slide (on or off)
- Instead of fill patterns, different features would be represented by different colours instead
- Dropdown menu for Countries would also have Continents (time permitting - nice to have not must have)
- Thought it would be cool to provide user with ability to toggle features on and off (time permitting - nice to have not must have)
- Please ignore thickness of scroll bar on Ranking of Happiness graph

Edits for Detailed View screen:
- Date should be a slider instead of a dropdown
- Max 4 features can be selected
- Max 10 countries (or continents) can be selected
- Where `Countries` is... Dropdown menu for Countries would also have Continents (time permitting - nice to have not must have)

**Comment by aidanmattrick** [comment]
This issue was closed by #10
